version: '2.1'

services:
  agent:
    image: golang:1.11
    working_dir: /code
    volumes:
      - ../:/code:cached
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"
